(define
    (convert-to-gif nb_of_frames top_line_text bottom_line_text gif_name)
(
    (let*
        (
         (image_id (car (gimp-image-new 608 360 0)))
         (frame_nb 0)
         (layer_id 0)
         (text_layer_id 0)
         (drawable 0)
         (frame_file_name "")
         (new_image_id 0)
         (floating_sel 0)
         (text "")
         (file_name (string-append gif_name ".gif"))
         (file_path (string-append "/home/fremis/Perso/gif_extractor/" file_name))
        )
        (set! text (string-append (string-append top_line_text "\n") bottom_line_text))
        (set! text_layer_id (car (gimp-text-layer-new image_id text "Impact Condensed" 50 0)))
        (gimp-image-insert-layer image_id text_layer_id 0 0)
        (gimp-text-layer-resize text_layer_id 608 360)
        (gimp-text-layer-set-color text_layer_id '(255 255 255))
        (gimp-text-layer-set-line-spacing text_layer_id 235)
        (gimp-text-layer-set-justification text_layer_id TEXT-JUSTIFY-CENTER)
        (gimp-layer-resize-to-image-size text_layer_id)
        (while (< frame_nb nb_of_frames)
            (set! frame_file_name (string-append "/home/fremis/Perso/gif_extractor/frame_" (number->string frame_nb)))
            (set! frame_file_name (string-append frame_file_name ".jpg"))
            (set! layer_id (aref (cadr (gimp-file-load-layers 1 image_id frame_file_name)) 0))
            (gimp-image-insert-layer image_id layer_id 0 0)
            (gimp-edit-copy text_layer_id)
            (gimp-edit-paste layer_id FALSE)
            (set! frame_nb (+ frame_nb 1))
        )
        (gimp-image-remove-layer image_id text_layer_id)
        (gimp-image-convert-indexed image_id 0 0 127 FALSE FALSE "")
        (set! drawable (car (gimp-image-get-active-drawable image_id)))
        (file-gif-save 1 image_id drawable file_path file_name 0 1 42 0)
    )
)
)
